version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: deployment/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
    restart: unless-stopped
